#include "Sampler.h"

namespace sark{

	// sampler id is automatically generated by constructor
	Sampler::Sampler(){
		glGenSamplers(1, &mSamplerId);
	}

	// sampler id is automatically deleted by destructor
	Sampler::~Sampler(){
		if (mSamplerId != 0)
			glDeleteSamplers(1, &mSamplerId);
	}

	// bind this sampler 
	void Sampler::Bind(uint16 activeTex) const{
		glBindSampler(activeTex, mSamplerId);
	}


	// set sampler parameter state
	void Sampler::SetState(State state, integer param){
		glSamplerParameteri(mSamplerId, state, param);
	}

	// set sampler parameter state
	void Sampler::SetState(State state, float32 param){
		glSamplerParameterf(mSamplerId, state, param);
	}

}